name: Atlas
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ariga/setup-atlas@v0
      - run: atlas version
      - name: Checkout
        uses: actions/checkout@v4
      - run: atlas migrate hash
      - run: atlas migrate lint --env test --base ${{ github.ref }}
