name: Atlas CI
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "migrations/*"
jobs:
  lint:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          env: ci
